DM-23283: Update nullable fields
lsst/sdm_schemas pull request #164
Opened 2023-11-22 18:33 UTC by bsmartradio

Change several fields from non-nullable to nullable

2023-11-22 19:06 UTC, ebellm approved these changes

2023-11-29 21:00 UTC, JeremyMcCormick requested changes
Please delete the .idea files that were added (presumably accidentally). They don't look like they belong in the repo.

The branch also needs an "Update with rebase," too.

2023-12-01 20:30 UTC, gpdf requested changes
I'm sorry for perhaps being fussy, but I'm concerned that the commit message buries the lede, as it were.  An at least equally important part of this PR is changing "Sigma" to "Err" in a number of places.  Because it's not mentioned in the commit message it leaves some question as to whether it's intentional (or, say, an inadvertent regression).  

Is this a remnant of work triggered by RFC-333?

The ticket reference in the PR title, to DM-23283, appears to be to something unrelated, a change to the handling of airmass.  The branch name, including DM-24283, is about Avro schema documentation.  Neither Jira ticket mentions the Sigma/Err change.

Could you update the commit message to clarify this, please?

There are also attribute names like `DiaObject.u_scienceFluxSigma` still in apdb.yaml.  Should those be changed as well?

Finally, I note that identically named DiaObject fields in imsim.yaml are still in the "FluxSigma" form.  Might it be preferable to change them at the same time?

Thank you!
-Gregory

2023-12-01 21:49 UTC, ebellm commented
@bsmartradio Can you comment on why `Sigma` changed to `Err` here?  This change happened in the force push after my review, it looks like.  Reading https://jira.lsstcorp.org/browse/RFC-333 I believe that that the original `Sigma` is correct, as we're characterizing the width of the distribution of DIASource fluxes associated with the DIAObject.

2023-12-04 18:06 UTC, gpdf approved these changes
This seems to be appropriately limited to the stated goals now.

Please be aware that there is at least one other approved pending pull request likely to be merged today, so please check that `main` hasn't changed, and then rebase accordingly if needed, before merging.

2023-12-05 19:51 UTC, gpdf commented
I'd encourage rebasing and merging this soon, as it seems it's fully signed-off - we're trying to clear a backlog of PRs on this repo.

2023-12-05 20:50 UTC, gpdf commented
OK, no worries.  If it's still in-work that's fine!

2023-12-20 22:51 UTC, JeremyMcCormick commented
I've marked this as a draft so it doesn't get unintentionally merged as it has been approved already, but there was an indication by @bsmartradio that work still needs to be done on it.

2024-01-03 02:01 UTC, merged