DM-42404: Deduplicate IDs to fix errors when loading schemas into TAP
lsst/sdm_schemas pull request #182
Opened 2024-01-18 19:54 UTC by JeremyMcCormick

2024-01-18 20:07 UTC, gpdf requested changes
Why only `i` and `z`?  Doesn't this affect all six?

2024-01-19 21:10 UTC, JeremyMcCormick commented
> Why only `i` and `z`? Doesn't this affect all six?

It does. There was some buggy code in felis that I fixed which was causing some of the duplicate IDs not to print. I fixed it, and I will update all of these fields.

2024-01-23 00:52 UTC, merged

2024-01-23 00:53 UTC, gpdf reviewed
Confirming that this change was OK.

2024-02-16 17:15 UTC, JeremyMcCormick commented
Branch name is wrong. The correct ticket under which this was resolved is [DM-42540](https://jira.lsstcorp.org/browse/DM-42540).