DM-41063: Add nan, suspect_long_trial, and off_image flags
lsst/sdm_schemas pull request #191
Opened 2024-03-06 23:02 UTC by bsmartradio

2024-03-06 23:32 UTC, gpdf reviewed
This is just a comment, not an objection.

These column names are starting to get very long, sometimes more than 50% of the length of the description.  Long column names are not going to be super-popular with users creating ADQL queries, and they also don't lead to a great UX in a visualization, because either one displays the whole string -- with associated distortions of the UI, like very wide columns that only have 'T' or 'F' in them -- or some generic truncation of it, which might not be nearly as informative as a deliberately constructed shorter name.

Note that the description string _is_ available in almost every context, Portal, PyVO, TOPCAT, etc.

I'm not requesting changes because we don't have a stated maximum length and we also haven't leaned hard on this in the past, but it would be good to think it through.

2024-05-02 23:11 UTC, mrawls approved these changes

2024-05-03 03:04 UTC, JeremyMcCormick requested changes

2024-05-03 03:04 UTC, JeremyMcCormick commented on yml/imsim.yaml
> +    mysql:datatype: BOOLEAN
Please remove all of these as they are redundant with `datatype: boolean` and will be flagged in the validation as errors in the near future.

2024-05-03 17:47 UTC, JeremyMcCormick commented
@bsmartradio You should pull recent updates to `main` and rebase your branch. Otherwise you are going to see erroneous validation errors in some of the other schemas.

2024-05-07 00:37 UTC, gpdf commented
The current state of this PR appears to be that it only changes one line of code, the description for the column `DiaSource.ext_trailedSources_Naive_flag_edge` .  Is that correct or is the branch still in flux?

2024-05-07 18:39 UTC, bsmartradio commented
This is still in flux as the other 5 PR's related to it are still in the works. This will likely be the only change and this PR will be updated.
________________________________
From: gpdf ***@***.***>
Sent: Monday, May 6, 2024 5:37 PM
To: lsst/sdm_schemas ***@***.***>
Cc: Brianna Smart ***@***.***>; Mention ***@***.***>
Subject: Re: [lsst/sdm_schemas] DM-41063: Add nan, suspect_long_trial, and off_image flags (PR #191)


The current state of this PR appears to be that it only changes one line of code, the description for the column DiaSource.ext_trailedSources_Naive_flag_edge . Is that correct or is the branch still in flux?

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/lsst/sdm_schemas/pull/191*issuecomment-2097150550__;Iw!!K-Hz7m0Vt54!m5gzBcs6NysWnSWkipTnxv0K48G4YHUVPtXyTk5HgWsOaonYzrG4pzLkmt9u6UvYUG_nR0SN1k3Ebq8jP1ocupA$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AWZRE6HYW273E736JC4AIYDZBAO4TAVCNFSM6AAAAABEJ5ZQZKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOJXGE2TANJVGA__;!!K-Hz7m0Vt54!m5gzBcs6NysWnSWkipTnxv0K48G4YHUVPtXyTk5HgWsOaonYzrG4pzLkmt9u6UvYUG_nR0SN1k3Ebq8jvlEhf4A$>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-05-08 02:12 UTC, JeremyMcCormick commented
> This is still in flux as the other 5 PR's related to it are still in the works. This will likely be the only change and this PR will be updated.

I do not feel like it is appropriate to use the ticket branch name `DM-41063` here, as that makes it seem like you are resolving the issue when this is just a comment change.

Maybe rename the branch to `DM-41063-update-comment` or something similar, especially if there are more PRs incoming.

In fact, if there are that many updates planned, I would suggest breaking up the ticket appropriately into child issues or it will be a mess keeping track of what has actually been resolved.

2024-05-08 02:44 UTC, JeremyMcCormick commented
> This is still in flux as the other 5 PR's related to it are still in the works. This will likely be the only change and this PR will be updated.

This is such a minor change that it should just be rolled into some other update or put on a user branch. We only real merge ticket branches like this when they attempt to resolve the issues that they are referencing in Jira.

> 5 PR's related to it are still in the works

It would be my preference that these are split into separate Jira issues and ticket branches. For anything but trivial changes we generally aim for a one-to-one correspondence between PRs and tickets on this project. There are exceptions to a patch/fix/update an already merged branch but generally this would be a good pattern to follow.

2024-05-08 15:56 UTC, bsmartradio commented
> > This is still in flux as the other 5 PR's related to it are still in the works. This will likely be the only change and this PR will be updated.
> 
> This is such a minor change that it should just be rolled into some other update or put on a user branch. We only really merge ticket branches like this when they resolve the connected Jira issue, and we don't reuse branch names or generally allow merging the same branch more than once.
> 
> > 5 PR's related to it are still in the works
> 
> It would be my preference that these are split into separate Jira issues and ticket branches. For anything but trivial changes we aim for a one-to-one correspondence between PRs and tickets on this project. There are exceptions when applying a small patch/fix/update to an already merged branch (with branch naming like `DM-12345-fixed-something`) or making minor updates on a user branch, but generally this would be a good pattern to follow for organizational purposes. It is also crucial for generating easily understandable release notes where each item should correspond to a resolved ticket.

I believe there may be some confusion, the other 5 PR's are the related ticket work for DM-41063 are in other packages. We are changing how the edge flag works and what it means across multiple packages to make it more specific when we filter the trailed sources. Naturally, this means that the docstring for the flag needs to be updated as it no longer is accurate since it now no longer indicates off image trails. If you still feel this requires a user branch, I can do that, but this is directly related to the edge flag change and migration in ticket DM-41063.

2024-05-08 19:31 UTC, JeremyMcCormick requested changes
> this is directly related to the edge flag change and migration in ticket DM-41063

The PR uses the branch `tickets/DM-41063`, which makes it seem like the issue is being resolved, when this only changes a comment. This means no one else should then use the same branch for updates on this issue, because we do not reuse branch names when they have been merged via a PR. (It is confusing and generally discouraged to merge the same branch more than once via a PR.)

> If you still feel this requires a user branch, I can do that, but this is directly related to the edge flag change and migration in ticket DM-41063.

I'm actually wondering why this shouldn't just be rolled into another PR that updates the schemas, since it is a very minor change. If you do want to make it a separate PR for some reason, then, yes, I think a user branch would be more appropriate here.

> the other 5 PR's are the related ticket work for DM-41063 are in other packages

Thank you for the clarification. That clears things up.

2024-05-08 20:33 UTC, JeremyMcCormick approved these changes
@bsmartradio indicated that the additional columns on the schemas were no longer needed and this PR resolves the work for the ticket on this repo.

2024-05-08 20:43 UTC, merged

2024-06-28 17:14 UTC, gpdf commented
@bsmartradio We just noticed that the description change in this ticket was applied only to `imsim.yaml` and not to the same `DiaSource.trail_flag_edge` attribute in `apdb.yaml`.  Was this an oversight?