Add missing lengths for columns with sized types
lsst/sdm_schemas pull request #212
Opened 2024-04-26 18:55 UTC by JeremyMcCormick

Felis will no longer accept columns with sized types that are missing a length. All such columns were updated to include explicit length values where they were missing.

Some columns had an existing `votable:arraysize` that was changed to a `length`. This value will be used automatically for the `arraysize` when generating the TAP_SCHEMA.

A few columns were changed from a sized string type to `text` where the VOTable type had been specified already as `clob`.

2024-05-02 00:24 UTC, gpdf requested changes
I don't think `ivoa.ObsPlan.o_ucd` in `obsloctap.yaml` should be changing from `string` to `char` -- that seems the reverse of the other changes and unless @womullan specifically wants this, it doesn't seem right.

2024-05-02 00:24 UTC, gpdf commented on yml/obsloctap.yaml
> +        datatype: char
Why is this one changing in the opposite direction?

2024-05-02 16:25 UTC, womullan approved these changes
in principle fine - I can not run felis just now as it seems to have changed I assume it still makes a valid postgres schema

2024-05-02 23:25 UTC, JeremyMcCormick commented
> it seems to have changed

You probably just need `felis create` instead of `felis create-all` as I did change the name of this command.

2024-05-03 15:04 UTC, womullan commented
yes indeed - ok now there are sizes on the varchars before they were just varchar - possibly better like this. I would not let it stop you merging and going ahead.

2024-05-03 16:39 UTC, gpdf commented
@womullan 
> ... now there are sizes on the varchars before they were just varchar - possibly better like this

Where exactly are you seeing this change?  In the Postgres schema generated from `obsloctap.yaml`?

2024-05-03 16:49 UTC, gpdf approved these changes
Ready to merge.  If Wil's observation requires further attention we'll file another ticket.

2024-05-03 16:50 UTC, merged

2024-05-05 15:58 UTC, womullan commented
@gpdf yes old schema      target_name VARCHAR, 
new schema 	target_name VARCHAR(40),