Change build engine to mysql / Enable size column in TAP_SCHEMA columns
lsst/sdm_schemas pull request #239
Opened 2024-07-06 00:17 UTC by stvoutsin

**Summary**
Add size value to the TAP_SCHEMA column entries that get inserted. This addresses the issue where validators expect the "size" column to match the "arraysize" col. 
The second change is to modify the engine-url to "mysql+mysqlconnector", as the TAP_SCHEMA  database currently deployed is in MySQL, so the insert statements need to be produced for that as far as I can see. I noticed this after trying to add values for the size column, which produced invalid SQL statements.

**Jira issue:**
https://rubinobs.atlassian.net/browse/DM-44878

**How was this tested**
- Tested on data-dev, using a custom Docker image built locally.
- Test run using stilts taplint

2024-07-06 00:27 UTC, stvoutsin commented
Depends on a fix to https://rubinobs.atlassian.net/browse/DM-45139

2024-07-08 15:40 UTC, JeremyMcCormick requested changes
Please split the changes to the two files into separate commits.

2024-08-05 23:51 UTC, gpdf approved these changes
Addition of 'size' is appropriate; unable to explicitly review possible consequences of change of `load-tap` to MySQL.

2024-08-05 23:57 UTC, JeremyMcCormick approved these changes
Requested changes were (separate commits for each file).

2024-08-05 23:57 UTC, merged