DM-46681: Update extendedness field description
lsst/sdm_schemas pull request #270
Opened 2024-10-23 19:28 UTC by abudlong

2024-10-23 22:10 UTC, JeremyMcCormick approved these changes

2024-10-28 16:25 UTC, JeremyMcCormick requested changes
Minor change request on https://github.com/lsst/sdm_schemas/pull/270/commits/9305ae893ae9e75e322d2b6feab34d12718da886

Please change "Adding" to "Add" so the commit message conforms to DM standards.

2024-10-28 22:13 UTC, JeremyMcCormick approved these changes

2024-10-28 22:15 UTC, merged

2024-10-28 22:40 UTC, parejkoj commented
@JeremyMcCormick : did you mean to merge this one? It's still in development, and had to be merged with the other related tickets.