Publish dp02Schema tap-schema to -stable,-int, and idfint
lsst/sdm_schemas pull request #44
Opened 2022-03-10 19:36 UTC by fritzm

2022-03-10 21:41 UTC, gpdf requested changes
I realize that this is not final. However, before its first deployment, can we at least harmonize the top level with what was done for DP0.1.  The "schema" for DP0.1 was named "dp01_dc2_catalogs".  Here it's just named "dp02".  I think the same logic applies for including "_dc2" this time, so we should just do that.  Regarding appending "_catalogs", that depends on whether the intent is to include the image metadata tables (the original "Exposure" and "Visit" tables) in the same "schema" (in the TAP sense of the word) as the catalogs.

One argument _against_ doing so (and therefore keeping "_catalogs" for DP0.2) is that we've talked about a model (in the final system) where we host the catalog tables only on Qserv, and the image metadata tables both on Qserv and in the Consolidated Database, because the image metadata tables are useful in both contexts.

2022-03-10 21:42 UTC, gpdf commented
For today's deployment I'll be happy if we just change to "dp02_dc2".

2022-03-10 22:01 UTC, fritzm commented
@gpdf done re. dp02_dc2 rename (though not sure why that was a particularly good name choice the first time?)

Is there also a preference/direction on top level "name:" and "@id:" in the yamls for dp0.1 and dp0.2 here?

2022-03-10 22:02 UTC, gpdf commented
It was decided in collaboration with the CET, to make it clear right up front that the delegates were working with DC2 data.

2022-03-15 20:51 UTC, rra commented
I don't really know much about this and will leave the review to Gregory.

2022-03-17 18:32 UTC, gpdf submitted a review, later dismissed

2022-03-17 18:32 UTC, gpdf commented on yml/dp02_dc2.yaml
> +"@id": dc2
I think this string should match the schema name, especially if we are also going to have a `dp02_dc2_images` schema added that needs to be distinguished from `dp02_dc2_catalogs`.

2022-03-17 18:32 UTC, gpdf commented on yml/dp02_dc2.yaml
> +"@id": dc2
Following this line, please add

`description: Preliminary schema for Data Preview 0.2, including only catalog tables for now`

2022-03-17 19:37 UTC, merged